server:
  port: 9001

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        exclude: '*'

spring:
  application:
    name: start-mgmt
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: mgmt-service-id
        serviceName: micro-${spring.application.name}
