server:
  port: 9003

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        exclude: '*'

spring:
  application:
    name: start-dict
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: micro-${spring.application.name}
