server:
  port: 9000

management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        exclude: '*'

spring:
  application:
    name: start-app
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: app-service-id
        serviceName: micro-${spring.application.name}
